// <auto-generated />
using BitirmeProjesi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitirmeProjesi.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20221206191347_TravelMigration")]
    partial class TravelMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BitirmeProjesi.Models.Anasayfa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("GoTourResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HakkimizdaYazisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriResmiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriYorum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Anasayfas");
                });

            modelBuilder.Entity("BitirmeProjesi.Models.Hakkimizda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AcenteIsim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcenteResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HakkimizdaSayfaYazisi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hakkimizdas");
                });

            modelBuilder.Entity("BitirmeProjesi.Models.Iletisim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("KisiResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Iletisims");
                });

            modelBuilder.Entity("BitirmeProjesi.Models.Turlar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("SehirIsim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurFiyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurKacGun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UlkeIsim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UlkeResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Turlars");
                });
#pragma warning restore 612, 618
        }
    }
}
